-- VHDL Entity My_Lib.protein5_s.symbol
--
-- Created:
--          by - mg30.bin (srge00.ecn.purdue.edu)
--          at - 16:08:14 08/28/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY protein5_s IS
   PORT( 
      I : IN     std_logic_vector (4 DOWNTO 0);
      O : OUT    std_logic
   );

-- Declarations

END protein5_s ;

--
-- VHDL Architecture My_Lib.protein5_s.struct
--
-- Created:
--          by - mg30.bin (srge00.ecn.purdue.edu)
--          at - 16:08:14 08/28/12
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF protein5_s IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din2  : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL in1   : std_logic;
   SIGNAL in2   : std_logic;
   SIGNAL in3   : std_logic;
   SIGNAL in4   : std_logic;
   SIGNAL out1  : std_logic;



BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 nand4
   -- eb1 1                                        
   out1 <= not (in1 and in2 and in3 and in4);


   -- ModuleWare code(v1.9) for instance 'U_8' of 'inv'
   O <= NOT(dout3);

   -- ModuleWare code(v1.9) for instance 'U_0' of 'nand'
   in3 <= NOT(I(3) AND I(2) AND I(0));

   -- ModuleWare code(v1.9) for instance 'U_1' of 'nand'
   in4 <= NOT(I(4) AND I(2) AND I(0));

   -- ModuleWare code(v1.9) for instance 'U_2' of 'nand'
   in2 <= NOT(I(4) AND I(2) AND I(1));

   -- ModuleWare code(v1.9) for instance 'U_3' of 'nand'
   dout1 <= NOT(I(2) AND I(1) AND I(0));

   -- ModuleWare code(v1.9) for instance 'U_4' of 'nand'
   dout <= NOT(I(3) AND I(2) AND I(1));

   -- ModuleWare code(v1.9) for instance 'U_5' of 'nand'
   din2 <= NOT(I(3) AND I(1) AND I(0));

   -- ModuleWare code(v1.9) for instance 'U_6' of 'nand'
   in1 <= NOT(I(4) AND I(1) AND I(0));

   -- ModuleWare code(v1.9) for instance 'U_9' of 'nand'
   dout2 <= NOT(dout AND dout1 AND din2);

   -- ModuleWare code(v1.9) for instance 'U_7' of 'nor'
   dout3 <= NOT(out1 OR dout2);

   -- Instance port mappings.

END struct;
